version: '3'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    env_file:
      - .env

  splitter:
    build: ./chopchop
    entrypoint: ["/app/wait-for-it.sh" , "minio:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/script.sh"]
    restart: always
    environment: 
      - TX=TRUE
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc
      - chopchop:/app/tmp

  joiner:
    build: ./chopchop
    entrypoint: ["/app/wait-for-it.sh" , "minio:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/script.sh"]
    restart: always
    environment: 
      - RX=TRUE
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc
      - chopchop:/app/tmp

  diode:
    build: ./chopchop
    entrypoint: ["/app/wait-for-it.sh" , "minio:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/diode.sh"]
    restart: always
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc

  janitor:
    build: ./chopchop
    entrypoint: ["/app/wait-for-it.sh" , "minio:9000" , "--strict" , "--timeout=300" , "--" , "bash" , "/app/janitor.sh"]
    restart: always
    env_file:
      - .env
    volumes: 
      - mc_config:/root/.mc

volumes: 
  mc_config:
  chopchop: